### PR TITLE
fix: persist navigation state

### LINKED ISSUE #355: Current screen is not persisted on reload
super annoying

### PR DESCRIPTION
**Pull request by jonathanlab**
closes #355

### CODE REVIEW

File: apps/array/src/renderer/components/MainLayout.tsx [hunk 1]
```diff
@@ -8,27 +8,35 @@ import { SettingsView } from "@features/settings/components/SettingsView";
...
     isOpen: shortcutsSheetOpen,
     toggle: toggleShortcutsSheet,
     close: closeShortcutsSheet,
   } = useShortcutsSheetStore();
+  const { data: tasks } = useTasks();
 
   useIntegrations();
   useTaskDeepLink();
 
+  useEffect(() => {
```
Comment (joshsny) [inline apps/array/src/renderer/components/MainLayout.tsx]: is this necessary, I think everything here is in a store, also why do we pass `tasks` to `hydrateTask`?

Should it be `hydrateTasks(tasks)` or `for task in tasks; hydrateTask(task)`?

**Review by joshsny — APPROVED** [review]
